services:
  frontend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - hackathon_network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - hackathon_network

  db:
    image: mariadb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hackathon_network

volumes:
  db_data:

networks:
  hackathon_network:
    driver: bridge
